<?php if($this->enableTracking()): ?>
    <script type="text/javascript">
        var _riseA = _riseA || [];
        _riseA.push([ 'setTracker', '<?php echo $this->getCode(); ?>' ]);

        (function() {
            var snrs = document.createElement('script');
            snrs.type = 'text/javascript';
            snrs.async = true;
            snrs.src = ('https:' == document.location.protocol ? 'https://'
                    : 'http://')
                + '<?php echo $this->getHost(); ?>/snrs-2.0.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(snrs, s);
        })();
    </script>

    <!-- SDK -->
    <script>
        function onSyneriseLoad() {
            SR.auth.trackerKey('<?php echo $this->getCode(); ?>');
            SR.init();
        }
        (function(s,y,n,e,r,i,se){s['SyneriseObjectNamespace']=r;s[r]=s[r]||[],s[r]._t=1*new Date(),
            s[r]._i=0,s[r]._l=i;var z=y.createElement(n),se=y.getElementsByTagName(n)[0];z.async=1;z.src=e;
            se.parentNode.insertBefore(z,se);z.onload=z.onreadystatechange=function(){var rdy=z.readyState;
                if(!rdy||/complete|loaded/.test(z.readyState)){s[i]();z.onload = null;z.onreadystatechange=null;}};
        })(window,document,'script','https://app.synerise.com/js/sdk/synerise-javascript-sdk-latest.min.js','SR', 'onSyneriseLoad');
    </script>
    <!-- end SDK -->

<?php endif;