<?php 
$id = Mage::app()->getRequest()->getParam('id');
$rule = Mage::getModel('salesrule/rule')->load($id);

if($rule->getSyneriseUuid()):
    $logoUrl = Mage::getBaseUrl('media') . 'synerise/logo.jpg';    
    $headMsg = $this->__("Price Rule created via Synerise Coupon module"); 
    $headStyle = "font-size:1.3em; margin:0.25em 0"; 
    $infoMsg = $this->__("<p>Basic options are editable only via <a href=\'https://app.synerise.com/coupons\' target=\'_blank\'>Synerise panel</a>.</p>")
        . $this->__("<p>Feel free to further define your rule, by managing <b>Websites</b> & <b>Customer Groups</b>, as well as setting some custom <b>Conditions</b> & <b>Actions</b>.</p>")
        . $this->__("<p><u>Note</u>: You can disable this rule locally by changing its status. Mind that deleting, won\'t stop it from being processed.</p><p>Enjoy!</p>");
    $infoStyle = "background: url('$logoUrl') no-repeat scroll -90px; "
        . "border: 1px solid #CCCCCC; "
        . "margin-bottom: 10px; "
        . "padding: 10px 10px 10px 250px; "
        . "min-height: 75px; "
        . "color: #6f8992; ";
    
    $html = '<div style=\"'.$infoStyle.'\"><h2 style=\"'.$headStyle.'\">'.$headMsg.'</h2>' . $infoMsg . '</div>';
    
?>
<script type="text/javascript">
//<![CDATA[
function disableSyneriseValues() {
    $$(".content-header").first().insert({ after: "<?php echo $html; ?>" });
    $('promo_catalog_edit_tabs_coupons_section_content').select('.entry-edit').first().remove();
    
    // fix fields
    $('rule_name').disable().hide().insert({ after: "<span>"+$('rule_name').getValue()+"</span>" });
    $('rule_description').disable().hide().insert({ after: "<span>"+$('rule_description').getValue()+"</span>" });
    $('rule_from_date').disable().hide().insert({ after: "<span>"+$('rule_from_date').getValue()+"</span>" });
    $('rule_from_date_trig').hide();
    $('rule_to_date').disable().hide().insert({ after: "<span>"+$('rule_to_date').getValue()+"</span>" });
    $('rule_to_date_trig').hide();
    
    $('rule_simple_action').disable().hide().insert({ after: "<span>"+$('rule_simple_action')[$('rule_simple_action').selectedIndex].text+"</span>" });
    $('rule_discount_amount').disable().hide().insert({ after: "<span>"+$('rule_discount_amount').getValue()+"</span>" });

    $('rule_uses_per_coupon').up(1).hide();
    $('rule_uses_per_customer').up(1).hide();    
    $('rule_coupon_type').up(1).hide();
    $('rule_coupon_code').up(1).hide();
    $('rule_use_auto_generation').up(1).hide();
}
document.observe("dom:loaded", disableSyneriseValues);
//]]>
</script>
<?php endif;