
<?php if(Mage::registry('current_product')): ?>
<?php $product = Mage::registry('current_product'); ?>
	<meta property="og:title" content="<?php echo ($product->getName()); ?>" />
	<meta property="og:type" content="product" />
<?php foreach ($product->getMediaGalleryImages() as $_image): ?>
        <meta property='og:image' content='<?php echo $_image->getUrl(); ?>'/>
<?php endforeach;?>
<?php foreach ($this->getCurrentProductCategories() as $_category): ?>
        <meta property='og:category' content='<?php echo $_category->getName(); ?>'/>
<?php endforeach;?>
	<meta property="og:url" content="<?php echo $product->getProductUrl(); ?>" />
<?php 
if($product->getShortDescription()) {
    $description = $product->getShortDescription();
} elseif($product->getDescription()) {
    $description = $product->getDescription();
}
if(isset($description)):
?>
	<meta property="og:description" content="<?php echo strip_tags($description); ?>" />
<?php endif; ?>
	<meta property="og:site_name" content="<?php echo Mage::getStoreConfig('general/store_information/name'); ?>" />        
        <meta property="product:original_price:amount" content="<?php echo $product->getPrice() ?>" />
        <meta property="product:original_price:currency" content="<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>" />
        <meta property="product:price:amount" content="<?php echo $product->getFinalPrice() ?>" />
        <meta property="product:price:currency" content="<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>" />        
	<meta property="product:retailer_part_no" content="<?php echo $product->getSku(); ?>" />        
<?php elseif(Mage::registry('current_category')): ?>
	<meta property="og:title" content="<?php echo $this->getTitle() ?>" />
	<meta property="og:type" content="product.group" />
	<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
	<meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
	<meta property="og:site_name" content="<?php echo Mage::getStoreConfig('general/store_information/name'); ?>" />        
<?php elseif((Mage::getSingleton('cms/page')->getIdentifier() == 'home'  &&
		Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms')) : ?>
	<meta property="og:title" content="<?php echo $this->getTitle() ?>" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
	<meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
	<meta property="og:site_name" content="<?php echo Mage::getStoreConfig('general/store_information/name'); ?>" />        
<?php else: ?>
	<meta property="og:title" content="<?php echo $this->getTitle() ?>" />
	<meta property="og:type" content="article" />
	<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
	<meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
	<meta property="og:site_name" content="<?php echo Mage::getStoreConfig('general/store_information/name'); ?>" />        
<?php endif; ?>
